version: '3.8'
services:
  database:
    container_name: my-logistics-database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .:/my-logistics
      - ./database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - my-logistics-common
  backend:
    container_name: my-logistics-backend
    build:
      context: ./backend/target/docker/stage
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - my-logistics-common
networks:
  my-logistics-common:
    name: my-logistics-common
    driver: bridge
