@startuml Storage Net ER Diagram

entity "User" as user {
  id
  hr_id
  nickname
  first_name
  last_name
}

entity "Manager" as manager {
  id
  user_id
}

entity "Administrator" as administrator {
  id
  user_id
}

entity "Supplier" as supplier {
  id
  name
  description
}

entity "Transporter" as transporter {
  id
  name
  description
}

entity "Customer" as customer {
  id
  name
  description
}

entity "Storage" as storage {
  id
  name
  location
  administrator
}

entity "Cell" as cell {
  id
  storage_id
  item_kind_id
  capacity
  placement_date
}

entity "Item Kind" as item_kind {
  id
  name
  expiration
  unit
}

entity "Item Group" as item_group {
  id
  item_kind_id
  amount
  manufacture_date
  order_id
}

entity "Order" as order {
  id
  customer_id
  creation_date
  deadline
  note
}

entity "Supply Request" as supply_request {
  id

  storage_id
  initiator_id
  transporter_id
  supplier_id

  approver_id
  approval_date

  creation_date
  action_date

  note
}

entity "Supply" as shipment {
  id
  supply_request_id
  date
}

entity "Withdrawal Request" as withdrawal_request {
  id
  
  storage_id
  order_id
  initiator_id
  transporter_id

  approver_id
  approval_date

  creation_date
  action_date

  note
}

entity "Withdrawal" as withdrawal {
  id
  withdrawal_request_id
  date
}

entity "Freeze" as freeze {
  id
  item_group_id
  start_date
  end_date
  note
}

entity "Transfer Request" as transfer_request {
  id

  initiator_id
  transporter_id
  source_storage_id
  destination_storage_id

  source_approver_id
  source_approval_date

  destination_approver_id
  destination_approval_date

  creation_date

  expected_begin_date
  expected_end_date

  note
}

entity "Transfer" as transfer {
  id

  transfer_request_id
  transporter_ride_id

  actual_begin_date
  actual_end_date
}


@enduml