# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Ensure Quality

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Scala
      uses: olafurpg/setup-scala@v11
      with:
        java-version: openjdk

    - name: Run formatter
      uses: openlawteam/scalafmt-ci@v2

    - name: Run unit tests
      run: sbt test
    
